name: Pick Old Branches & Owners

on:
  workflow_dispatch:

jobs:
  PickOldBranchesOwners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0  # Needed to retrieve full commit log
      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.x'

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Find Stale Branches and List Owners
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          #AGE_CUTOFF=360 # In days
          AGE_CUTOFF=10 # In days
          #MAIN_BRANCH=master
          MAIN_BRANCH=main

          echo "This is the workflow of Reza"

          # Fetch all branches
          git branch -r | grep -v '\->' | sed 's/origin\///' > branches.txt

          contributorsList=()
          # Loop through branches
          while read branch; do
            # Skip main branch
            if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
              echo "  Main branch: ${branch}. Skipping..."
              continue
            fi

            # Skip if open PR exists
            open_prs=$(gh pr list --head "$branch" --json number --jq 'length')
            if [ "$open_prs" -gt 0 ]; then
              echo "There exists an open PR for branch $branch..."
              continue
            fi

            # Get last commit date
            lastCommitDate=$(gh api repos/${{ github.repository }}/commits/$branch --jq '.commit.committer.date')

            # Calculate branch age in days
            branchAgeDays=$(( ($(date -u +%s) - $(date -u -d "$lastCommitDate" +%s)) / 86400 ))

            # Check whether the branch is old enough
            if [ $branchAgeDays -lt $AGE_CUTOFF ]; then
              echo "  Branch $branch is still active. Last commit $branchAgeDays days ago. Skipping..."
            else
              echo "  Branch $branch is $branchAgeDays days old. Archiving..."
              
              # Get contributors to the branch
              contributors=$(gh api repos/${{ github.repository }}/compare/$MAIN_BRANCH...$branch --jq '.commits[] | "  - \(.commit.author.name) (@\(.author.login))  "' | sort | uniq)
              
              #contributorsList+="Reza"
              #contributorsList+=contributors
            fi
          done < branches.txt
          #echo "List of contributors to the old branches: ${contributorsList[@]}"
 