name: Remove A Single Old Branch

on:
  workflow_dispatch:
    inputs:
      age_cutoff:
        description: 'Branches older than this many days'
        required: true
        default: '10' # In days
        type: number

      branch_name:
        description: 'The name of the old branch to remove'
        required: true
        default: ""
        type: string	

jobs:
  RemoveSingleOldBranch:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for branch deletion
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0  # Needed to retrieve full commit log

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip google-genai

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Find Stale Branches and List Owners
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  
        run: |
          branch="${{ inputs.branch_name }}"
          if [ -z "$branch" ]; then
            echo "Error: No branch name was provided."
            exit 1
          fi
          echo $branch

          AGE_CUTOFF=${{ inputs.age_cutoff }} # In days
          echo $AGE_CUTOFF

          #MAIN_BRANCH=master
          MAIN_BRANCH=main
  
          # Fetch all branches
          git branch -r | grep -v '\->' | sed 's/origin\///' > branches.txt

          # Loop through branches-----------------------------------------------
          #while read branch; do
          # Skip main branch
          if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
            exit 1
          fi

          # Skip if open PR exists
          open_prs=$(gh pr list --head "$branch" --json number --jq 'length')
          if [ "$open_prs" -gt 0 ]; then
            exit 1
          fi

          # Get last commit date
          echo "lastCommitDate0 ="${{ github.repository }}
          lastCommitDate=$(gh api repos/${{ github.repository }}/commits/$branch --jq '.commit.committer.date')
          echo "lastCommitDate"
  
          # Calculate branch age in days
          branchAgeDays=$(( ($(date -u +%s) - $(date -u -d "$lastCommitDate" +%s)) / 86400 ))
          echo "branchAgeDays="$branchAgeDays
          # Check whether the branch is old enough
          if [ $branchAgeDays -ge $AGE_CUTOFF ]; then
            # Get number of new commits
            commitCount=$(gh api repos/${{ github.repository }}/compare/$MAIN_BRANCH...$branch --jq '.commits | length')
            echo "commitCount="$commitCount
            if [ $commitCount -gt 0 ]; then
               # Format the last commit date
               lastCommitDateF=$(date -u -d "$lastCommitDate" +"%B %d, %Y")

               # Get the first commit date (index 0 is the oldest commit in the diff)
               firstCommitDate=$(gh api repos/${{ github.repository }}/compare/$MAIN_BRANCH...$branch --jq '.commits[0].commit.committer.date')
               firstCommitDateF=$(date -u -d "$firstCommitDate" +"%B %d, %Y")
               echo "firstCommitDate"
       
               ## Get contributors to the branch
               #contributors=$(gh api repos/${{ github.repository }}/compare/$MAIN_BRANCH...$branch --jq '.commits[] | "  - \(.commit.author.name) (@\(.author.login))  "' | sort | uniq)
	       #
               ## Get a summary of the branch changes using Google's Gemini AI
               #diff=$(git diff origin/$MAIN_BRANCH...origin/$branch)
               #summary=$(python .github/workflows/create_pr_summary.py <<< "$diff")
               #echo $summary

               ## Create the PR body with contributors
               #prBody="## **Archiving branch \`$branch\`**
               #- **Last commit on:** $lastCommitDateF
               #- **First commit on:** $firstCommitDateF  
               #- **Total number of commits:** $commitCount  
               #- **Contributors:**  
               #$contributors  
               ### Changes Summary  
               #*(Generated using Gemini AI)*  
               #$summary"
               ##echo $prBody
               ##printf '%q\n' "$prBody"
               
               # Create PR, close PR, and delete the branch
               echo "  Create PR for ${branch}..."
               #gh pr create --title "[Archive] Branch \"$branch\"" --body "$prBody" --base $MAIN_BRANCH --head $branch >/dev/null 2>&1 || true
               #gh pr create --title "[Archive] Branch \"feature2\"" --body "I created PR manually" --base main --head feature2

               commitData=$(gh api "repos/${{ github.repository }}/compare/$MAIN_BRANCH...$branch")
               contributors=$(printf '%s\n' "$commitData" | jq -r '.commits[] | select(.author.login != null) | "\(.commit.author.name) (@\(.author.login))"' | sort -u)
               contributors=$(printf '%s\n' "$contributors" | paste -sd ', ' -)

               BLUE='\033[34m'
               RED='\033[31m'
               GREEN='\033[32m'
               NC='\033[0m'
               printf "BRANCH=${BLUE}%-20s${NC} AGE=${RED}%-20s${NC} OWNER=${GREEN}%s${NC}\n" "$branch" "${branchAgeDays} days old" "$contributors"
            fi
          fi
          #done < branches.txt-----------------------------------------