name: Reza Original YML
on: 
  workflow_dispatch:
jobs:
  RezaOriginalArchiveOldBranches:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
    
