name: test0625

on:
  workflow_dispatch:

jobs:
  ArchiveStaleBranches:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for branch deletion
      pull-requests: write
    steps:
      - name: Checkout
        #uses: actions/checkout@v4
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0  # Needed to retrieve full commit log
